### ISSUE TITLE
[ Feature Request ]

### ISSUE THREAD

**Issue by Techsh0w** [arashnm80/spot-seek-bot#4]
Hi
Would you please consider add zip download option for albums or playlists?
It would be great, thank you for your amazing work.

**Comment by arashnm80** [comment]
Hello
Thank you for your feedback, it really means a lot to me.
About your recommendation: One of the reasons that make the bot fast enough is that it doesn't spend time and energy for redownloading repetitive songs and uploading them to telegram. it just forwards them from previous executions. this makes the bot able to send tens of songs per second and it won't occupy server's storage for any tracks because all of them are stored in telegram servers.
But if I add zip download option whether songs are repetitive or not the bot will have to redownload them, spend cpu energy to archive them and reupload the zip file to telegram. Also even if one of the playlist tracks changes it has to do this process all over again because previous zip file would be useless.
